# Generated by Django 5.0.4 on 2024-04-04 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('mobile_no', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[7-9]{1}+[0-9]{9}')])),
                ('issue', models.TextField()),
            ],
        ),
    ]
